[package_info]
name = "binutils"
version = "2.38"
from = "https://ftp.gnu.org/gnu/binutils/binutils-2.38.tar.xz"
sudo_req = true
compression_method = "xz"
after_compression = "binutils-2.38"
[how_to_install]
to_run = """
mkdir -v build
cd build
../configure
make
make install
"""