[package_info]
name = "binutils"
version = "2.38"
from = "https://ftp.gnu.org/gnu/binutils/binutils-2.38.tar.xz"
compression_method = "xz"
after_compression = "binutils-2.38"
build_dir = true
[configure]
how_to = "../configure --disable-nls --disable-werror"
[build]
how_to = "make -j4"
[install]
how_to = "make install"
need_sudo = true